export const LOADER_START = "LOADER_START";
export const LOADER_STOP = "LOADER_STOP";
export const POPUP_OPEN = "POPUP_OPEN";
export const POPUP_CLOSE = "POPUP_CLOSE";
export const AUTH_TOKEN = "AUTH_TOKEN";
export const FIELD_ERRORS = "FIELD_ERRORS";
export const GET_CURRENT_USER_DETAILS = "GET_CURRENT_USER_DETAILS";
export const CREATE_A_NEW_BLOG = "CREATE_A_NEW_BLOG";
export const SET_BLOG = "SET_BLOG";
export const CLEAR_BLOG = "CLEAR_BLOG";
export const FETCH_ALL_BLOG = "FETCH_ALL_BLOG";
export const FETCH_SINGLE_BLOG = "FETCH_SINGLE_BLOG";
export const UPDATE_SINGLE_BLOG = "UPDATE_SINGLE_BLOG";
export const DELETE_SINGLE_BLOG = "DELETE_SINGLE_BLOG";

// Files upload

export const UPLOAD_ARTICLE_FILES = "UPLOAD_ARTICLE_FILES";

// MAIN TAB ARTICLES API

export const HOME_PAGE_ARTICLES = "HOME_PAGE_ARTICLES";
export const KASAR_HAUSA_PAGE_ARTICLES = "KASAR_HAUSA_PAGE_ARTICLES";
export const AFRIKA_PAGE_ARTICLES = "AFRIKA_PAGE_ARTICLES";
export const DUNIYA_PAGE_ARTICLES = "DUNIYA_PAGE_ARTICLES";
export const KASUWANCI_PAGE_ARTICLES = "KASUWANCI_PAGE_ARTICLES";
export const WASANNI_PAGE_ARTICLES = "WASANNI_PAGE_ARTICLES";
export const WASANNI_PAGE_NEWS_FEEDS_ARTICLES =
  "WASANNI_PAGE_NEWS_FEEDS_ARTICLES";
export const YANAYI_PAGE_ARTICLES = "YANAYI_PAGE_ARTICLES";

// AFRICA REGION PAGE API
export const AFRIKA_REGION_MAIN_SECTION_ARTICLES =
  "AFRIKA_REGION_MAIN_SECTION_ARTICLES";
export const AFRIKA_REGION_NEWS_FEED_SECTION_ARTICLES =
  "AFRIKA_REGION_NEWS_FEED_SECTION_ARTICLES";
